### ISSUE TITLE
troubles after updating 

### ISSUE THREAD

**Issue by MobinShekari84** [tobhe/ubuntu-asahi#132]
after using "sudo apt update" and "sudo apt upgrade, computer is running super slow and it delays so much.

thanks for helping

![image](https://github.com/user-attachments/assets/b33bd3f2-7487-441c-a8ed-f4f36afbe883)

**Comment by tobhe** [comment]
looks like something is wrong, and apt failed to update some packages. The computer is probably slow because a mismatch between kernel and graphics drivers.

Your screenshot does not include enough information to tell what exactly went wrong, can you try to include a little more info?  What happens if you try to update again?

**Comment by MobinShekari84** [comment]
![image](https://github.com/user-attachments/assets/844f981d-63ad-4c0d-af7d-554a64b60f36)
![image](https://github.com/user-attachments/assets/e486a267-a7cd-4f3e-87b8-555f02a42227)
![image](https://github.com/user-attachments/assets/42666318-fe33-474d-933a-2b7c607b16a4)

**Comment by tobhe** [comment]
Thanks, so I see multiple problems there.

1. The vscode repo doesn't seem to work because of a missing key. You should be able to fix that by following the keyring instructions here https://code.visualstudio.com/docs/setup/linux
2. The update seems to fail because of a openrazer-driver package you have installed which doesn't seem to work with the latest kernel. try removing that before updating.

**Comment by VladimirKadlec** [comment]
I had a similar problem, in my case it was evdi driver that didn't compile with 6.10 kernel . During the update, the mesa package was updated, but the kernel was not. So after a reboot the desktop was not accelerated, this message appears in the syslog:
`UABI mismatch: Kernel 10010, Mesa 10011`
Maybe the mesa package(s) (not sure which ones) should depend on the kernel package?

**Comment by tobhe** [comment]
Thanks for the added context @VladimirKadlec, I suppose we can try solving the next UAPI transition a bit nicer with an explicit dependency. It still won't be perfect because we don't have a solution if the kernel installs correctly but doesn't work as expected and you want to go back to the old one but we can certainly do better than currently.
