### ISSUE TITLE
install app

### ISSUE THREAD

**Issue by seyedanvari** [tobhe/ubuntu-asahi#31]
how to inatall the ubuntu app ? i try install nekoray and fail .
What features must the app have to be installed?

**Comment by tobhe** [comment]
Hi @seyedanvari. I would recommend to install applications from the "Ubuntu software" application or via the command line with apt, see https://ubuntu.com/server/docs/package-management.

Some applications might not work properly on arm64 or because they make assumptions about the hardware which are not true for Apple Silicon machines, but most applications I use actually work without problems.

If you find that an application does not work as expected you might want to open a bug with the original author and see if they are interested in fixing it.
