### ISSUE TITLE
GPU drivers

### ISSUE THREAD

**Issue by HeshamAbdelgawad** [tobhe/ubuntu-asahi#33]
When will the gpu drivers for ubuntu-asahi be released?

**Comment by tobhe** [comment]
Hi @HeshamAbdelgawad. GPU drivers are supported in kinetic and newer. Which version are you using?

**Comment by HeshamAbdelgawad** [comment]
I am using lunar

**Comment by tobhe** [comment]
Is this a fresh install or updated from a previous release? Can you share what `cat /etc/apt/sources.list.d/asahi-ppa.list` and `apt list --installed | grep asahi` return for you?

**Comment by HeshamAbdelgawad** [comment]
![image](https://github.com/tobhe/ubuntu-asahi/assets/73796068/8cd36b0a-06a9-40e6-bc4b-62fcb1d3c8c3)

**Comment by tobhe** [comment]
so kernel and mesa are there and no `/etc/apt/sources.list.d/asahi-ppa.list` means this is a relatively new installation. Try `cat /etc/apt/sources.list.d/extra-ppas.list` instead but since this is a new installation I guess this shouldn't be the issue.

Why do you think the GPU is not working? What does `glxinfo | grep -C 4 Accelerated` give you (you might need to install `mesa-utils` for that)?

**Comment by HeshamAbdelgawad** [comment]
It says next to acceleration yes.
15 minutes ago, when i executed "screenfetch", the gpu section was empty, but now it recognized "apple m1".
thanks for your help.

**Comment by tobhe** [comment]
Weird, but I'm glad it works now :) Closing this bug for now. Feel free to reopen this if it happens again.
