### ISSUE TITLE
Compile and Install a Linux Kernel

### ISSUE THREAD

**Issue by gaoxiangliu** [tobhe/ubuntu-asahi#36]
Hi,

After installing an Ubuntu OS on Mac Mini M1, is it possible to compile a Linux kernel from the source code (kernel.org) and install it? So, next time when booting up into the Ubuntu system, the kernel will be the self-built kernel. If so, what is the recommended configuration of it?

Thanks.

**Comment by tobhe** [comment]
Mainline kernels won't work well because they lack all the Asahi and Ubuntu patches. If you want to build the ubuntu-asahi kernel by hand you could start from https://github.com/UbuntuAsahi/linux.

You can find the configuration in [debian.asahi/config/config.common.ubuntu](https://github.com/UbuntuAsahi/linux/blob/ubuntu/debian.asahi/config/config.common.ubuntu).
