### ISSUE TITLE
While updating to Kinetic, the update magically failed to install and after a reboot, my Ubuntu install is f*cked up.

### ISSUE THREAD

**Issue by SamilKaraduman** [tobhe/ubuntu-asahi#4]
No grub boot menu, so not much I can do.

**Comment by tobhe** [comment]
Any idea why it failed? where does it hang after reboot? In general a failed upgrade is pretty bad news, you might be able to switch to a tty via ctrl - alt - f2 and try to figure out what is wrong from there.

**Comment by SamilKaraduman** [comment]
I'm really not sure, but here is a video clip.

**Comment by SamilKaraduman** [comment]
https://user-images.githubusercontent.com/83664323/209448137-b23491f4-fea2-4eb0-8bb0-b2d3cf7a16ee.mov

**Comment by tobhe** [comment]
This looks like some failure in the graphics pipeline, probably a bug in mesa in combination with the newest kernel. I am surprised because we had a similar bug at one point that I assumed was fixed with a recent update. As I said above, you should be able to switch to a tty and run `apt update && apt upgrade` by hand to fix it.

**Comment by SamilKaraduman** [comment]
That did the trick. Thanks a lot!
