### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by MingshanHe** [tobhe/ubuntu-asahi#56]
Hi, Thanks for your excellent work.

Is it planned to support Ubuntu 20.04 system?

Bests-,
Mingshan

**Comment by tobhe** [comment]
No, I think it is safe to say that there won't be any support for older versions. 22.04 is already tricky to support, 20.04 was before the m1 hit the consumer market so all the bug fixes in random packages since then aren't included yet.

What do you need 20.04 for? Maybe your problem can be solved by running a 20.04 container on an up-to-date host.

**Comment by MingshanHe** [comment]
Thanks for your reply. I am recommended to use ROS1 (Robot Operating System) in Ubuntu 20.04 which is not supported in Ubuntu 22.04 yet.
