### ISSUE TITLE
safe to install alongside sonoma ?

### ISSUE THREAD

**Issue by space192** [tobhe/ubuntu-asahi#60]
as the title imply, is it safe ?

**Comment by tobhe** [comment]
I have not tried but there is no reason to assume it isn't. The asahi installer creates a separate partition with everything it needs, so once installed a macos upgrade should work without problems.

Trying to install Ubuntu from Sonoma might give you a firmware error because we currently don't allowlist 13.5, see: https://github.com/UbuntuAsahi/ubuntu-asahi/issues/59

I expect that to be fixed soon, I just need to test it.

**Comment by space192** [comment]
Yeah I was thinking about the firmware version specifically ahah I'm gonna look at #59 :D
